version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - FINANCIAL_DATASETS_API_KEY=${FINANCIAL_DATASETS_API_KEY}
    expose:
      - "8000"
    command: ["uvicorn", "dexter.server:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_DEXTER_API_BASE: ${NEXT_PUBLIC_DEXTER_API_BASE:-http://localhost:8000}
    environment:
      - NEXT_PUBLIC_DEXTER_API_BASE=${NEXT_PUBLIC_DEXTER_API_BASE:-http://backend:8000}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["npm", "run", "start"]
